### ISSUE TITLE
Memory Dump functions needed.

### ISSUE THREAD

**Issue by Sugarsplash** [Sugarsplash/ece485#1]
Will someone please write a set of functions to display all the contents of the M2array and M3array. Would be useful for development. Might also be a good idea to zero out the memory arrays as well.

**Comment by vertexmachina** [comment]
Will do today.

**Comment by Sugarsplash** [comment]
Looks like memory is already zeroed at init.

**Comment by vertexmachina** [comment]
Done. Also added constructors to zero-out the memory because I noticed
sometimes it had garbage, sometimes not. Better to be safe.

Compile mem.cpp with satellite.cpp to see the printing.

**Comment by Sugarsplash** [comment]
Looks Great!
